export const storeData=[
    {
        id:1,
        name:"saiteja",
        department:"software",
        phone:8247373032,
        edit:false
    },{
        id:2,
        name:"krishna",
        department:"Finance",
        phone:9086754712,
        edit:false
    },{
        id:3,
        name:"venky",
        department:"HR",
        phone:9086754123,
        edit:false
    },{
        id:4,
        name:"kesav",
        department:"IT",
        phone:9086751234,
        edit:false
    },{
        id:5,
        name:"harsha",
        department:"Banking",
        phone:9086754766,
        edit:false
    },{
        id:6,
        name:"basha",
        department:"Revenue",
        phone:9086754766,
        edit:false
    },{
        id:7,
        name:"vinodh",
        department:"Rural",
        phone:9086754766,
        edit:false
    },{
        id:8,
        name:"murali",
        department:"Tourism",
        phone:9087689089,
        edit:false
    },{
        id:9,
        name:"srikanth",
        department:"Home",
        phone:7890890789,
        edit:false
    },{
        id:10,
        name:"gopi",
        department:"Urban",
        phone:8907890098,
        edit:false
    },{
        id:11,
        name:"gopi",
        department:"Urban",
        phone:8907890098,
        edit:false
    },{
        id:12,
        name:"gopi",
        department:"Urban",
        phone:8907890098,
        edit:false
    },{
        id:13,
        name:"gopi",
        department:"Urban",
        phone:8907890098,
        edit:false
    },{
        id:14,
        name:"gopi",
        department:"Urban",
        phone:8907890098,
        edit:false
    },{
        id:15,
        name:"gopi",
        department:"Urban",
        phone:8907890098,
        edit:false
    },{
        id:16,
        name:"gopi",
        department:"Urban",
        phone:8907890098,
        edit:false
    },{
        id:17,
        name:"gopi",
        department:"Urban",
        phone:8907890098,
        edit:false
    },{
        id:18,
        name:"gopi",
        department:"Urban",
        phone:8907890098,
        edit:false
    },{
        id:19,
        name:"gopi",
        department:"Urban",
        phone:8907890098,
        edit:false
    },{
        id:20,
        name:"gopi",
        department:"Urban",
        phone:8907890098,
        edit:false
    },
]